#include "Precompile.h"
#include <DxLib.h>
#include <fstream>
#include <sstream>
#include <vector>
#include "ShareClass.h"
#include <memory>
#include <stdio.h>
#include <cassert>
#include "Vector2.h"
#include "Rect.h"
